version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    cooldown:
      default-days: 5
    assignees:
      - "0xflotus"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:30"
    assignees:
      - "0xflotus"
